# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import securemsg.models


class Migration(migrations.Migration):

    dependencies = [
        ('securemsg', '0005_auto_20160830_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='keymaster',
            name='adder_slug',
            field=models.SlugField(default=securemsg.models.randomString),
        ),
        migrations.AlterField(
            model_name='keymaster',
            name='confirmation_token',
            field=models.CharField(db_index=True, default=securemsg.models.randomString, max_length=32),
        ),
    ]
