# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securemsg', '0002_auto_20160830_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_blob', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='publickey',
            name='public_key',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='public_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securemsg.PublicKey'),
        ),
    ]
