# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securemsg', '0004_auto_20160830_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('confirmation_token', models.CharField(db_index=True, max_length=32)),
                ('confirmed', models.BooleanField(default=False)),
                ('public_key', models.TextField()),
                ('private_key_file', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='datarequest',
            name='public_key',
        ),
        migrations.AddField(
            model_name='datarequest',
            name='key_master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='securemsg.KeyMaster'),
            preserve_default=False,
        ),
    ]
