# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securemsg', '0006_auto_20160831_1513'),
        ('securemsg', '0006_auto_20160831_1646'),
    ]

    operations = [
    ]
